media:
  input: static
  output: /
content:
  - name: homepage
    label: Homepage
    path: content/_index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true
  - name: saisons
    label: Saisons
    path: content/saisons
    type: collection
    subfolders: true
    exclude:
      - _index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
        required: true
      - name: publishDate
        label: Publish Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
        required: true
      - name: image
        label: Image
        type: image
        required: true
      - name: concertId
        label: Concert ID
        type: string
        required: true
      - name: homepage
        label: Homepage
        type: string
      - name: musicians
        label: Musicians
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
        required: true
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      layout: tree
      node:
        filename: _index.md
      default:
        search: ''
        sort: date
        order: desc
  - name: infos
    label: Infos
    path: content/infos.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: type
        label: Type
        type: select
        options:
          values: [ special ]
        required: true
      - name: layout
        label: Layout
        type: select
        options:
          values: [ simple ]
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true