media:
  input: static
  output: /
content:
  - name: homepage
    label: Homepage
    path: content/_index.md
    type: file
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: subtitle
        label: Subtitle
        type: text
        required: true
  - name: saisons
    label: Saisons
    path: content/saisons
    type: collection
    subfolders: true
    exclude:
      - _index.md
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: publishDate
        label: Publish Date
        type: date
        required: true
      - name: image
        label: Image
        type: image
        required: true
      - name: concertId
        label: Concert ID
        type: string
        required: true
      - name: homepage
        label: Homepage
        type: string
      - name: musicians
        label: Musicians
        type: string
        list: true
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      layout: tree